repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-json
    - id: mixed-line-ending
      args: ['--fix=lf']
      description: Forces to replace line ending by the UNIX 'lf' character.
-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
    -   id: autopep8
        args:
        - -i
        - --max-line-length=90
        - --ignore=E402
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.257'
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix]
