name: build-and-test

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
  push:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install requirements
        run: pip install -r requirements.txt

      - name: smoketest
        run: |
          cd ./src
          python repo_import.py --help

      - name: test
        run: |
          cd ./tests
          python -m unittest discover ./ -v
