name: build-and-test

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
  push:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive      

      - name: install requirements
        run: |
         pip install -r requirements.txt
         pip install -r libs/dspace-rest-python/requirements.txt

      - name: smoketest
        run: |
          cd ./src
          python repo_import.py --help
